
### Get All Companies

GET http://localhost:3000/companies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

### Get Company

GET http://localhost:3000/companies/7
# SUpER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4
# ADMIN
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA0OjEwOjMyLjkwM1oiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDQ6MTA6MzIuOTAzWiIsImNvbXBhbnlJZCI6MSwiaWF0IjoxNzIwNzU2NTQ4LCJleHAiOjE3MjA4NDI5NDh9.Hr9SwRn75Gjj2KOCnAfglvsCFKki0S3H9cKPjm2c2o4
# GERENTE
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsIm5hbWUiOiJHZXJlbnRlIC0gSGVsaWNlIiwiZW1haWwiOiJnZXJlbnRlQGdtYWlsLmNvbSIsInJvbGUiOiJHRVJFTlRFIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTEyVDAzOjQ0OjQ2LjY3OVoiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTJUMDM6NDQ6NDYuNjc5WiIsImNvbXBhbnlJZCI6MiwiaWF0IjoxNzIwNzU2ODQ5LCJleHAiOjE3MjA4NDMyNDl9.C6iCqOq5ktrKyxpteXYlo4HLbJy1E1Q6HKOAPLUkU_o


### Get Users by Company

GET http://localhost:3000/companies/8/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4


### Create company

POST  http://localhost:3000/companies
Content-Type: application/json
# SUpER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

{
  "name": "Tesla"
}

### Delete company

DELETE  http://localhost:3000/companies/8
Content-Type: application/json
# SUpER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

