
### Get All Companies

GET http://localhost:3000/companies
Authorization: Bearer {TOKEN}

### Get Company

GET http://localhost:3000/companies/7
# SUpER
Authorization: Bearer {TOKEN}

### Get Users by Company

GET http://localhost:3000/companies/8/users
Authorization: Bearer {TOKEN}


### Create company

POST  http://localhost:3000/companies
Content-Type: application/json
# SUpER
Authorization: Bearer {TOKEN}

{
  "name": "Tesla"
}

### Delete company

DELETE  http://localhost:3000/companies/8
Content-Type: application/json
# SUpER
Authorization: Bearer {TOKEN}
