### List All Machines
GET http://localhost:3000/machines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

### Get By Id Machine

GET http://localhost:3000/machines/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

### Create machine

POST http://localhost:3000/machines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

{
  "name": "INC NOVA",
  "type": "INC",
  "ip": "192.168.0.99"
}

### Delete Machine

DELETE http://localhost:3000/machines/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4
