### List All Machines
GET http://localhost:3000/machines
Authorization: Bearer {TOKEN}

### Get By Id Machine

GET http://localhost:3000/machines/10
Authorization: Bearer {TOKEN}

### Create machine

POST http://localhost:3000/machines
Content-Type: application/json
Authorization: Bearer {TOKEN}

{
  "name": "NAS 1",
  "type": "NAS",
  "ip": "192.168.0.3",
  "companyId": 1
}


### Create machine

PATCH http://localhost:3000/machines/2
Content-Type: application/json
Authorization: Bearer {TOKEN}

{
  "name": "INC 1"
}

### Delete Machine

DELETE http://localhost:3000/machines/9
Authorization: Bearer {TOKEN}
