
### List All Users
// TOKEN SUPER: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA0OjU4OjAzLjMwNFoiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDQ6NTg6MDMuMzA0WiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjc0MDM4LCJleHAiOjE3MjA3NjA0Mzh9.5BZETXpr3jRNM5k-OYuhwUYjriG43Wfv7NFWuQzMRik
// TOKEN GERENTE: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsIm5hbWUiOiJHZXJlbnRlIiwiZW1haWwiOiJnZXJlbnRlQGdtYWlsLmNvbSIsInJvbGUiOiJHRVJFTlRFIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA0OjUzOjAyLjgzNVoiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDQ6NTM6MDIuODM1WiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjczNjIyLCJleHAiOjE3MjA3NjAwMjJ9.aAUUQ9Rgcqox_C7ctMI5YE4tO3totiQrrPk1h_8lQHg

GET http://localhost:3000/users?page=1&pageSize=10
# SUpER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4
# ADMIN
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA0OjEwOjMyLjkwM1oiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDQ6MTA6MzIuOTAzWiIsImNvbXBhbnlJZCI6MSwiaWF0IjoxNzIwNzU2NTQ4LCJleHAiOjE3MjA4NDI5NDh9.Hr9SwRn75Gjj2KOCnAfglvsCFKki0S3H9cKPjm2c2o4
# GERENTE
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsIm5hbWUiOiJHZXJlbnRlIC0gSGVsaWNlIiwiZW1haWwiOiJnZXJlbnRlQGdtYWlsLmNvbSIsInJvbGUiOiJHRVJFTlRFIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTEyVDAzOjQ0OjQ2LjY3OVoiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTJUMDM6NDQ6NDYuNjc5WiIsImNvbXBhbnlJZCI6MiwiaWF0IjoxNzIwNzU2ODQ5LCJleHAiOjE3MjA4NDMyNDl9.C6iCqOq5ktrKyxpteXYlo4HLbJy1E1Q6HKOAPLUkU_o

### Get By Id

GET http://localhost:3000/users/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

### Get By Company

GET http://localhost:3000/users/company/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4


### Create User

POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4

{
  "name": "ADMIN Z",
  "email": "adminZ@tesla.com",
  "password": "admin",
  "companyId": 10,
  "role": "ADMIN"
}

### Delete User

DELETE http://localhost:3000/users/31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJTdXBlciIsImVtYWlsIjoic3VwZXJAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSIiwiY3JlYXRlQXQiOiIyMDI0LTA3LTExVDA2OjQwOjUxLjg2MloiLCJ1cGRhdGVBdCI6IjIwMjQtMDctMTFUMDY6NDA6NTEuODYyWiIsImNvbXBhbnlJZCI6bnVsbCwiaWF0IjoxNzIwNjgwMDY2LCJleHAiOjE3MjA3NjY0NjZ9.y4hD-ZrtkSZOB5UU2YF8OrHHZTMDpDgFe1EHbb2KGE4
