
### List All Users
GET http://localhost:3000/users?page=1&pageSize=10
Authorization: Bearer {TOKEN}

### Get By Id

GET http://localhost:3000/users/24
Authorization: Bearer {TOKEN}

### Get By Company

GET http://localhost:3000/users/company/7
Authorization: Bearer {TOKEN}


### Create User

POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer{TOKEN}

{
  "name": "Jon",
  "email": "jon25@tesla.com",
  "password": "admin",
  "companyId": 10,
  "role": "ADMIN"
}

### Delete User

DELETE http://localhost:3000/users/31
Authorization: Bearer {TOKEN}
